### Create a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "user",
    "email": "user@local.com",
    "password": ""
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "user@local.com",
    "password": "password"
}

### Logout (requires Authorization header)
POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ1c2VyQGxvY2FsLmNvbSIsImlhdCI6MTczNzAxNjQyMiwiZXhwIjoxNzM3MDIwMDIyfQ.j91vvJIzqeZdszzzx8kJhwQXSGwZyDCJ_uS1FBif4p0


### Get all users
GET http://localhost:3000/auth/users
Content-Type: application/json

### Get a single user by ID
GET http://localhost:3000/auth/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ1c2VyQGxvY2FsLmNvbSIsImlhdCI6MTczNzAxNjQyMiwiZXhwIjoxNzM3MDIwMDIyfQ.j91vvJIzqeZdszzzx8kJhwQXSGwZyDCJ_uS1FBif4p0


### Create a new user
POST http://localhost:3000/auth/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": ""
}

### Update a user by ID
PUT http://localhost:3000/auth/users/1
Content-Type: application/json

{
    "name": "John Doe Updated",
    "email": "john.doe.updated@example.com"
}

### Delete a user by ID
DELETE http://localhost:3000/auth/users/1
Content-Type: application/json

